spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: TresFortMotDePasse123!
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      # set both limits to the same value (must have request >= file)
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9091
